# cf-lambda-vpc-infrastructure.yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Lambda VPC Infrastructure (Security Group and IAM Role)"

Parameters:
  AppShortName:
    Type: String
    Description: Application short name
    Default: 'healthb'

  EnvName:
    Type: String
    Description: Environment name
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-stg
      - nprd-sit1
      - nprd-sit2
      - nprd-sit3
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-sit-c
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b
      - nprd-uat-c
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - nprd-pp-c
      - prod
      - prod-a
      - prod-b
      - prod-c
    Default: nprd

  LambdaRoleName:
    Type: String
    Description: "Name of the IAM Role for the Lambda function"
    
  # ManagedPolicyArns:
  #   Type: CommaDelimitedList
  #   Description: "Comma-separated list of managed policy ARNs"
    
  SecurityGroupName:
    Type: String
    Description: "Name of the Security Group"
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID where the Security Group will be created"

Conditions:
  IsProduction: !Or 
    - !Equals [!Ref EnvName, prod]
    - !Equals [!Ref EnvName, prod-a]
    - !Equals [!Ref EnvName, prod-b]
    - !Equals [!Ref EnvName, prod-c]
    
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaRoleName
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-BackendLambda-v1
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
      # ManagedPolicyArns: !Ref ManagedPolicyArns
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    DeletionPolicy: !If [IsProduction, Retain, Delete]

  BaseExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${LambdaRoleName}-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "lambda:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "ec2:CreateNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DeleteNetworkInterface"
            Resource: "*"
          - Effect: Allow
            Action:
              - "xray:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "cloudwatch:PutMetricData"
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "logs:DescribeLogStreams"
            Resource: "*"
          - Effect: Allow
            Action:
              - "secretsmanager:*"
            Resource: "*"
      Roles:
        - !Ref LambdaExecutionRole

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref SecurityGroupName
      GroupDescription: "Lambda Security Group"
      SecurityGroupEgress:
          - CidrIp: "0.0.0.0/0"
            Description: "from 0.0.0.0/0:1-65535"
            FromPort: 1
            IpProtocol: "tcp"
            ToPort: 65535
      VpcId: !Ref VpcId
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-BackendLambda-v1
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    DeletionPolicy: !If [IsProduction, Retain, Delete]

  # SSM Parameters
  LambdaRoleArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/lambda/${AppShortName}/${EnvName}/execution-role-arn"
      Type: String
      Value: !GetAtt LambdaExecutionRole.Arn
      Description: "Lambda base execution role ARN"

  SecurityGroupIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/lambda/${AppShortName}/${EnvName}/security-group-id"
      Type: String
      Value: !Ref LambdaSecurityGroup
      Description: "Lambda security group ID"

Outputs:
  RoleArn:
    Description: ARN of the created IAM Role
    Value: !GetAtt LambdaExecutionRole.Arn
  RoleName:
    Description: Name of the created IAM Role
    Value: !Ref LambdaExecutionRole
  SecurityGroupId:
    Description: ID of the created Security Group
    Value: !Ref LambdaSecurityGroup
  SSMRoleArnPath:
    Description: SSM Parameter path for Lambda Role ARN
    Value: !Sub "/lambda/${EnvName}/base-role-arn"
  SSMSecurityGroupPath:
    Description: SSM Parameter path for Security Group ID
    Value: !Sub "/lambda/${EnvName}/security-group-id"