AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create or update an ECS Task Definition using Fargate with configurable OS, memory, CPU, ECR image, container name, port mappings, logging, and store output in Parameter Store.

Parameters:
  AppShortName:
    Description: Application name
    Type: String

  EnvName:
    Description: Env Name
    Type: String
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-sit1
      - nprd-sit2
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b      
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - prod
      - prod-a
      - prod-b

  VpcId:
    Description: VPC to create endpoints and workspace
    Type: AWS::EC2::VPC::Id

  ECRImage:
    Type: String
    Description: "The link to the ECR image (e.g., 533267434948.dkr.ecr.ap-southeast-1.amazonaws.com/hxis-fhir-ecr-repo:stable-alpine)"

  ECSCpuArchitecture:
    Type: String
    AllowedValues:
      - X86_64
      - ARM64
    Description: "The CPU architecture for the task (e.g., X86_64, ARM64)"
    Default: "X86_64"

  CPUUnits:
    Description: number of cpu units used by the task
    Type: String
    Default: 256

  Memory:
    Description: The amount (in MiB) of memory used by the task
    Type: String
    Default: 512

  ECSClusterName:
    Description: ECS Cluster Name
    Type: String

  ECSOperatingSystemFamily: 
    Type: String
    Description: "Operating system family to be used for the task. Allowed values are LINUX or WINDOWS versions."
    AllowedValues: 
      - LINUX
    Default: "LINUX"

  ECSServiceProtocol:
    Type: String
    AllowedValues:
      - HTTP
      - HTTPS
    Description: "The protocol used for the port mapping in target group (eg, http or https)"

  ServiceContainerPort:
    Type: Number
    Description: "The port on which the container listens (e.g., 80, 443, Custom Port)"

  ContainerProtocol:
    Type: String
    AllowedValues:
      - tcp
      - udp
    Description: "The protocol used for the port mapping (e.g., tcp, udp)"
    Default: "tcp"

  CreateNewTaskDefinition:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Description: "Choose 'true' to create a new Task Definition family or 'false' to create a new revision of an existing Task Definition."

  ExistingTaskFamily:
    Type: String
    Description: "The existing ECS task definition family name stored in Parameter Store. Leave blank if creating a new task definition."
    Default: ""

  ECSDesiredTaskCount:
    Type: Number
    Description: Number of desired tasks to run
    Default: 1

  VPCSubnetCidrAppAZ1:
    Description: CIDR block for the ECS service traffic
    Type: String
 
  VPCSubnetCidrAppAZ2:
    Description: CIDR block for the ECS service traffic
    Type: String

  VPCSubnetCidrAppAZ3:
    Description: CIDR block for the ECS service traffic
    Type: String

  AppSubnetIds:
    Type: CommaDelimitedList
    Description: List of subnet IDs where the ECS tasks will be deployed
    Default: subnet-08170d48a795103d2,subnet-083fba964c347656f,subnet-0e54709c5b9c524e1
  
  ECSALBListenerArn:
    Type: String
    Description: ALB Listener Arn that Target Group will be attached
    Default: "arn:aws:elasticloadbalancing:ap-southeast-1:781576980265:listener/app/seed-nprd-dev-alb-ecs/4da3f2ae6f737402/56b469288deb06d4"

  TargetGroupName:
    Description: ALB TargetGroup Name for container service
    Type: String

  PathPattern:
    Description: Path-pattern for ALB listerner Rule condition check to route it to specific target group
    Type: String

  TGHealthCheckPath:
    Description: ALB TargetGroup HealthCheck Path
    Type: String

  ServiceName:
    Description: ECS Service Name
    Type: String

  LogsRetentionInDays:
    Description: ECS Service Name
    Type: String
    Default: "7"

  RulePriority:
    Description: ALB Listener Rules Priority
    Type: String
    Default: "2"
  
  EnvVar1Name:
    Description: "Environment Variable #1 Name"
    Type: String

  EnvVar1Value:
    Description: "Environment Variable #1 Value"
    Type: String

  EnvVar2Name:
    Description: "Environment Variable #2 Name"
    Type: String

  EnvVar2Value:
    Description: "Environment Variable #2 Value"
    Type: String

  EnvVar3Name:
    Description: "Environment Variable #3 Name"
    Type: String

  EnvVar3Value:
    Description: "Environment Variable #3 Value"
    Type: String

  EnableAutoScaling:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: Enable or disable auto-scaling for the ECS service

  MinContainers:
    Type: Number
    Default: 1
    Description: Minimum number of containers to run

  MaxContainers:
    Type: Number
    Default: 4
    Description: Maximum number of containers to run

  CPUUtilizationThreshold:
    Type: String
    Default: 70
    Description: CPU utilization threshold for auto-scaling (percentage)

  MemoryUtilizationThreshold:
    Type: String
    Default: 70
    Description: Memory utilization threshold for auto-scaling (percentage)

  SecretName:
    Type: String
    Description: Name of the secret in Secrets Manager

Conditions:
  IsProduction: !Or [!Equals [!Ref "EnvName", "prod"], !Equals [!Ref "EnvName", "prod-a"], !Equals [!Ref "EnvName", "prod-b"]]
  HasEnvVar1Name: !Not [!Equals [!Ref EnvVar1Name, '']]
  HasEnvVar2Name: !Not [!Equals [!Ref EnvVar2Name, '']]
  HasEnvVar3Name: !Not [!Equals [!Ref EnvVar3Name, '']]

  CreateNewTaskDefinitionCondition:
    Fn::Equals: [!Ref CreateNewTaskDefinition, "true"]

  HasSubnetCidrAppAZ3: !Not [!Equals [!Ref VPCSubnetCidrAppAZ3, '']]
  EnableAutoScalingCondition: !Equals [!Ref EnableAutoScaling, 'true']

Resources:
  # Target Group
  ECSALBTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${AppShortName}-${EnvName}-${TargetGroupName}-tg-ecs"
      VpcId: !Ref VpcId
      Protocol: !Ref ECSServiceProtocol
      Port: !Ref ServiceContainerPort
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckProtocol: !Ref ECSServiceProtocol
      HealthCheckPort: !Ref ServiceContainerPort
      HealthCheckPath: !Ref TGHealthCheckPath
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      Matcher:
        HttpCode: "200"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'

  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ECSALBListenerArn
      Priority: !Ref RulePriority
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref PathPattern # Match requests to specific path
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ECSALBTG

  # CloudWatch Log Group Resource
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      LogGroupName: !Sub "/ecs/${AppShortName}/${EnvName}/${ServiceName}"
      RetentionInDays: !Ref LogsRetentionInDays  # Adjust the retention period as needed

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Family: !If
        - CreateNewTaskDefinitionCondition
        - !Sub "${AppShortName}-${EnvName}-${ServiceName}"  # New family
        - !Ref ExistingTaskFamily  # Use existing family from Parameter Store if provided
      Cpu: !Ref CPUUnits
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Sub "{{resolve:ssm:/${AppShortName}/${EnvName}/ECSTaskExecutionRoleArn}}"
      RuntimePlatform:
        CpuArchitecture: !Ref ECSCpuArchitecture
        OperatingSystemFamily: !Ref ECSOperatingSystemFamily
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref ECRImage
          PortMappings:
            - ContainerPort: !Ref ServiceContainerPort
              Protocol: !Ref ContainerProtocol
              AppProtocol: http
          Essential: true
          Secrets:
            - Name: ConnectionStrings__Local
              ValueFrom: !Sub '{{resolve:secretsmanager:${SecretName}:SecretString:ConnectionStrings__Local}}'
            - Name: ConnectionStrings__FhirMetadata
              ValueFrom: !Sub '{{resolve:secretsmanager:${SecretName}:SecretString:ConnectionStrings__FhirMetadata}}'
          Environment:
            - Name: OTEL_EXPORTER_OTLP_ENDPOINT
              Value: !Sub "http://adot-collector.${ECSClusterName}:4317"
            - !If
              - HasEnvVar1Name
              - Name: !Ref EnvVar1Name
                Value: !Ref EnvVar1Value
              - !Ref "AWS::NoValue"
            - !If
              - HasEnvVar2Name
              - Name: !Ref EnvVar2Name
                Value: !Ref EnvVar2Value
              - !Ref "AWS::NoValue"
            - !If
              - HasEnvVar3Name
              - Name: !Ref EnvVar3Name
                Value: !Ref EnvVar3Value
              - !Ref "AWS::NoValue"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogGroup  # Referencing the created log group
              awslogs-region: ap-southeast-1
              awslogs-stream-prefix: "ecs"
              mode: "non-blocking"
              max-buffer-size: "25m"
          StopTimeout: 120  #Adjust this value based on your application needs, max is 120 seconds for Fargate (If not configured, default is 30s)


## ECS Service/Container Setup
  ECSServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      GroupName: !Sub "${AppShortName}-${EnvName}-sg-ecs-${ServiceName}"
      GroupDescription: Security group for ECS Service
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ServiceContainerPort
          ToPort: !Ref ServiceContainerPort
          CidrIp: !Ref VPCSubnetCidrAppAZ1
          Description: App Subnet CIDR AZ1
        - IpProtocol: tcp
          FromPort: !Ref ServiceContainerPort
          ToPort: !Ref ServiceContainerPort
          CidrIp: !Ref VPCSubnetCidrAppAZ2
          Description: App Subnet CIDR AZ2
        - !If
          - HasSubnetCidrAppAZ3
          - IpProtocol: tcp
            FromPort: !Ref ServiceContainerPort
            ToPort: !Ref ServiceContainerPort
            CidrIp: !Ref VPCSubnetCidrAppAZ3
            Description: App Subnet CIDR AZ3
          - !Ref "AWS::NoValue"
        - IpProtocol: tcp
          FromPort: !Ref ServiceContainerPort
          ToPort: !Ref ServiceContainerPort
          SourceSecurityGroupId: !Sub "{{resolve:ssm:/${AppShortName}/${EnvName}/ecs-alb-security-group-id}}"
          Description: Allow traffic from ALB Security Group

  ECSService:
    Type: AWS::ECS::Service
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      ServiceName: !Sub "${AppShortName}-${EnvName}-${ServiceName}"
      Cluster: !Ref ECSClusterName
      TaskDefinition: !Ref ECSTaskDefinition
      LaunchType: FARGATE
      DesiredCount: !Ref ECSDesiredTaskCount
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSServiceSecurityGroup
          Subnets: !Ref AppSubnetIds
      LoadBalancers:
        - TargetGroupArn: !Ref ECSALBTG
          ContainerName: !Sub ${AppShortName}-${EnvName}-${ServiceName}
          ContainerPort: !Ref ServiceContainerPort
      HealthCheckGracePeriodSeconds: 0
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: '{{resolve:ssm:/ecs/serviceconnect/namespacearn}}'

  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: EnableAutoScalingCondition
    DependsOn: ECSService
    Properties:
      MaxCapacity: !Ref MaxContainers
      MinCapacity: !Ref MinContainers
      ResourceId: !Join 
        - '/'
        - - service
          - !Ref ECSClusterName
          - !Ref ServiceName
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService

  AutoScalingPolicyCPU:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: EnableAutoScalingCondition
    Properties:
      PolicyName: !Sub ${ServiceName}-cpu-autoscaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: !Ref CPUUtilizationThreshold
        ScaleInCooldown: 300
        ScaleOutCooldown: 300

  AutoScalingPolicyMemory:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: EnableAutoScalingCondition
    Properties:
      PolicyName: !Sub ${ServiceName}-memory-autoscaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        TargetValue: !Ref MemoryUtilizationThreshold
        ScaleInCooldown: 300
        ScaleOutCooldown: 300