AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to provision and deploy a private API with swagger json file
Parameters:
  AppShortName:
    Type: String
    Description: AppShortName

  EnvName:
    Type: String
    Description: Environment
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-dev1
      - nprd-dev2
      - nprd-sit1
      - nprd-sit2
      - nprd-sit3
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-sit-c
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b
      - nprd-uat-c      
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - nprd-pp-c
      - prod
      - prod-a
      - prod-b
      - prod-c

  LambdaS3bucket:
    Type: String
    Description: The s3 bucket where Lambda code is stored

  CodeZipFileName:
    Type: String
    Description: Zip file name for lambda function code

  LambdaRuntime:
    Type: String
    Description: Zip file name for lambda function code

  LambdaHandler:
    Type: String
    Description: Zip file name for lambda function code

  AzureAdClientId:
    Type: String
    Description: Azure AD Client ID
  
  AzureAdTenantId:
    Type: String
    Description: Azure AD Tenant ID

  ForwardProxyAddress:
    Type: String
    Description: Forward Proxy Address

Conditions:
  IsProduction: !Or [!Equals [!Ref "EnvName", "prod"], !Equals [!Ref "EnvName", "prod-a"], !Equals [!Ref "EnvName", "prod-b"], !Equals [!Ref "EnvName", "prod-c"]]

Resources:
  # Lambda Authorizer function
  LambdaAuthorizerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${AppShortName}-${EnvName}-LambdaAuthorizer'
      Handler: !Ref LambdaHandler # Adjust according to your Lambda code
      Role: !GetAtt LambdaAuthorizerRole.Arn  # Replace with your Lambda execution role ARN
      Runtime: !Ref LambdaRuntime # Adjust runtime as per your Lambda code
      Code:
        S3Bucket: !Ref LambdaS3bucket  # Replace with your S3 bucket where Lambda code is stored
        S3Key: !Ref CodeZipFileName # Replace with the key to your zipped Lambda function code
      Environment:
        Variables:
          AZURE_AD_TENANT_ID: !Ref AzureAdTenantId
          AZURE_AD_CLIENT_ID: !Ref AzureAdClientId
          FORWARD_PROXY_ADDRESS: !Ref ForwardProxyAddress
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-PrivateApi-v3

  LambdaAuthorizerRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain     
    Properties:
      RoleName: !Sub ${AppShortName}-${EnvName}-lambda-authorizer-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AppShortName}-${EnvName}-LambdaAuthorizerExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AppShortName}-${EnvName}-lambda-authorizer:*"
        - PolicyName: LambdaAuthorizerVPCAccessExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                Resource: "*"
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-PrivateApi-v3

#Outputs:
#  ApiGatewayUrl:
#    Description: 'URL of the API Gateway'
#    Value: !Sub 'https://${PrivateApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
