AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a private ALB in 2 AZs with IP and custom security group name, and store outputs in Parameter Store.

Parameters:
  AppShortName:
    Description: Application name in lower case
    Type: String

  EnvName:
    Description: Environment Name
    Type: String
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-sit1
      - nprd-sit2
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b      
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - prod
      - prod-a
      - prod-b
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the ALB will be created.

  VPCSubnetCidrAppAZ1:
    Type: String
    Description: VPC Subnet CIDR for App AZ1

  VPCSubnetCidrAppAZ2:
    Type: String
    Description: VPC Subnet CIDR for App AZ2

  VPCSubnetCidrAppAZ3:
    Type: String
    Description: VPC Subnet CIDR for App AZ3
    Default: ''

  ALBSubnetIds:
    Type: CommaDelimitedList
    Description: The Subnet IDs for App Subnets where the ECS ALB will be deployed.

  VPCSubnetCidrInternetAlbAZ1:
    Type: String
    Description: Internet ALB Subnet CIDR for AZ1 (optional)
    Default: ''

  VPCSubnetCidrInternetAlbAZ2:
    Type: String
    Description: Internet ALB Subnet CIDR for AZ2 (optional)
    Default: ''

  VPCSubnetCidrInternetAlbAZ3:
    Type: String
    Description: Internet ALB Subnet CIDR for AZ3 (optional)
    Default: ''

  HealthCheckPath:
    Type: String
    Description: Health Check Path for ALB and NLB

  ContainerPort:
    Type: Number
    Description: The port number on the container bound to the host port

  DefaultCertificateArn:
    Type: String
    Description: ARN of the default SSL certificate

  AdditionalCertificateArn:
    Type: String
    Description: ARN of the additional SSL certificate

Conditions:
  IsProduction: !Or 
    - !Equals [!Ref EnvName, prod]
    - !Equals [!Ref EnvName, prod-a]
    - !Equals [!Ref EnvName, prod-b]
  HasVPCSubnetCidrAppAZ3: !Not [!Equals [!Ref VPCSubnetCidrAppAZ3, '']]
  HasVPCSubnetCidrInternetAlbAZ1: !Not [!Equals [!Ref VPCSubnetCidrInternetAlbAZ1, '']]
  HasVPCSubnetCidrInternetAlbAZ2: !Not [!Equals [!Ref VPCSubnetCidrInternetAlbAZ2, '']]
  HasVPCSubnetCidrInternetAlbAZ3: !Not [!Equals [!Ref VPCSubnetCidrInternetAlbAZ3, '']]

Resources:
  # Security Group for ALB
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      GroupName: !Sub "${AppShortName}-${EnvName}-sg-alb-ecs"
      GroupDescription: Security group for the private ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VPCSubnetCidrAppAZ1
          Description: Allow traffic from NLB in AZ1
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VPCSubnetCidrAppAZ2
          Description: Allow traffic from NLB in AZ2
        - !If
          - HasVPCSubnetCidrAppAZ3
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: !Ref VPCSubnetCidrAppAZ3
            Description: Allow traffic from NLB in AZ3
          - !Ref "AWS::NoValue"
        - !If
          - HasVPCSubnetCidrInternetAlbAZ1
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: !Ref VPCSubnetCidrInternetAlbAZ1
            Description: Allow inbound from Internet ALB Subnet AZ1
          - !Ref "AWS::NoValue"
        - !If
          - HasVPCSubnetCidrInternetAlbAZ2
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: !Ref VPCSubnetCidrInternetAlbAZ2
            Description: Allow inbound from Internet ALB Subnet AZ2
          - !Ref "AWS::NoValue"
        - !If
          - HasVPCSubnetCidrInternetAlbAZ3
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: !Ref VPCSubnetCidrInternetAlbAZ3
            Description: Allow inbound from Internet ALB Subnet AZ3
          - !Ref "AWS::NoValue"

  # Application Load Balancer
  PrivateALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Name: !Sub "${AppShortName}-${EnvName}-alb-ecs"
      Subnets: !Ref ALBSubnetIds
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Scheme: internal
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'

  # Listener
  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            MessageBody: "404 Not Found"
            StatusCode: "404"
      LoadBalancerArn: !Ref PrivateALB
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref DefaultCertificateArn

  # Listener Rule for Health Check
  ALBHealthCheckListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Actions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            MessageBody: "ALB is healthy"
            StatusCode: "200"
      Conditions:
        - Field: path-pattern
          Values:
            - /health
            - /health/*
      ListenerArn: !Ref HTTPSListener
      Priority: 1

  Additional Listener Certificate
  ALBListenerCertificate:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties:
      Certificates:
        - CertificateArn: !Ref DefaultCertificateArn      
        - CertificateArn: !Ref AdditionalCertificateArn
      ListenerArn: !Ref HTTPSListener

  # SSM Parameters
  ALBSecurityGroupIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AppShortName}/${EnvName}/ecs-alb-security-group-id
      Type: String
      Value: !Ref ALBSecurityGroup
      Description: ALB Security Group ID
