AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to provision and deploy a private API with a Swagger JSON file.

Parameters:
  AppShortName:
    Type: String
    Description: AppShortName
    Default: "healthb"

  EnvName:
    Type: String
    Description: Environment
    Default: "nprd"

  LambdaS3bucket:
    Type: String
    Description: The S3 bucket where Lambda code is stored.
    Default: "health-nprd-cftemplates"

  CodeZipFileName:
    Type: String
    Description: Zip file name for Lambda function code.
    Default: "HealthBuddy.Authorizer-1.0.0.6.zip"

  LambdaRuntime:
    Type: String
    Description: Runtime for the Lambda function (e.g., nodejs14.x).
    Default: dotnet8

  LambdaHandler:
    Type: String
    Description: Handler for the Lambda function.
    Default: "Authorizer::HealthBuddy.Authorizer.Function::FunctionHandler"

  LambdaTimeout:
    Type: Number
    Description: Timeout for the Lambda authorizer function in seconds.
    Default: 90
    MinValue: 1
    MaxValue: 900

  AzureAdClientId:
    Type: String
    Description: Azure AD Client ID.
    Default: ""

  AzureAdTenantId:
    Type: String
    Description: Azure AD Tenant ID.
    Default: ""

  ForwardProxyAddress:
    Type: String
    Description: Forward Proxy Address.
    Default: ""

  SecurityGroupId:
    Type: String
    Description: Security group ID to attach to the Lambda function.
    Default: "sg-048257d88871b1a16"

  LogRetentionInDays:
    Type: Number
    Description: Log retention period in days.
    Default: 14

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs for the Lambda function

Conditions:
  HasAzureAdClientId: !Not [!Equals [!Ref AzureAdClientId, ""]]
  HasAzureAdTenantId: !Not [!Equals [!Ref AzureAdTenantId, ""]]
  HasForwardProxyAddress: !Not [!Equals [!Ref ForwardProxyAddress, ""]]

Resources:
  LambdaAuthorizerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${AppShortName}-${EnvName}-LambdaAuthorizer'
      Handler: !Ref LambdaHandler
      Role: !GetAtt LambdaAuthorizerRole.Arn
      Runtime: !Ref LambdaRuntime
      Timeout: !Ref LambdaTimeout
      Code:
        S3Bucket: !Ref LambdaS3bucket
        S3Key: !Ref CodeZipFileName
      Environment:
        Variables:
          Environment: !Ref EnvName
          AZURE_AD_TENANT_ID: !If [HasAzureAdTenantId, !Ref AzureAdTenantId, !Ref "AWS::NoValue"]
          AZURE_AD_CLIENT_ID: !If [HasAzureAdClientId, !Ref AzureAdClientId, !Ref "AWS::NoValue"]
          FORWARD_PROXY_ADDRESS: !If [HasForwardProxyAddress, !Ref ForwardProxyAddress, !Ref "AWS::NoValue"]
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds: !Ref SubnetIds
      TracingConfig:
        Mode: Active
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-BackendLambda-v1.2

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AppShortName}-${EnvName}-LambdaAuthorizer"
      RetentionInDays: !Ref LogRetentionInDays
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-BackendLambda-v1.2

  LambdaAuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppShortName}-${EnvName}-lambda-authorizer-role'
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-BackendLambda-v1.2
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${AppShortName}-${EnvName}-LambdaAuthorizerExecutionPolicy'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AppShortName}-${EnvName}-LambdaAuthorizer:*"
        - PolicyName: LambdaAuthorizerVPCAccessExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                Resource: "*"
        - PolicyName: LambdaAuthorizerXRayWriteAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: "*"

Outputs:
  LambdaAuthorizerArn:
    Description: ARN of the Lambda Authorizer function
    Value: !GetAtt LambdaAuthorizerFunction.Arn

  LambdaAuthorizerName:
    Description: Name of the Lambda Authorizer function
    Value: !Ref LambdaAuthorizerFunction

  LambdaAuthorizerRoleArn:
    Description: ARN of the Lambda Authorizer IAM Role
    Value: !GetAtt LambdaAuthorizerRole.Arn

  LambdaAuthorizerRoleName:
    Description: Name of the Lambda Authorizer IAM Role
    Value: !Ref LambdaAuthorizerRole
