AWSTemplateFormatVersion: 2010-09-09
Description: Provision NLB with ALB Target Group
Parameters:
  AppShortName:
    Type: String
    Description: AppShortName
  EnvName:
    Type: String
    Description: Environment
  Function:
    Type: String
    Description: Server Function (eg, APP, UTL, DB)
    AllowedValues:
      - APP
      - WEB
      - DB
      - UTL
  SubnetIdappAZ1:
    Type: String
    Description: VPC Subnet id for App AZ1
  SubnetIdappAZ2:
    Type: String
    Description: VPC Subnet id for App AZ2
  SubnetIdappAZ3:
    Type: String
    Description: VPC Subnet id for App AZ3
  IngressALBArn:
    Type: String
    Description: Ingress ALB Arn
  VpcId:
    Type: String
    Description: VPC ID
Conditions:
  IsProduction: !Or [!Equals [!Ref "EnvName", "prod"], !Equals [!Ref "EnvName", "prod-a"], !Equals [!Ref "EnvName", "prod-b"], !Equals [!Ref "EnvName", "prod-c"]]
Resources:
  IngressNLB:
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]  
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      IpAddressType: "ipv4"
      Subnets:
      - !Ref SubnetIdappAZ1
      - !Ref SubnetIdappAZ2
      - !If [IsProduction, !Ref SubnetIdappAZ3, !Ref "AWS::NoValue"]   
      Type: "network"
      Scheme: "internal"
      Name: !Sub ${AppShortName}-${EnvName}-${Function}-ingress-NLB
      SubnetMappings:
      - SubnetId: !Ref SubnetIdappAZ1
      - SubnetId: !Ref SubnetIdappAZ2
      - !If [IsProduction, {SubnetId: !Ref SubnetIdappAZ3}, !Ref "AWS::NoValue"]
      Tags:
        - Key: IaCVersion
          Value: InfraPlatform-EKS-v1

  IngressNLBTG:
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete] 
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      IpAddressType: "ipv4"
      HealthCheckIntervalSeconds: 30
      Matcher:
        HttpCode: "200-399"
      HealthCheckPath: "/health/ready"
      Port: 443
      Targets:
      - Port: 443
        Id: !Ref IngressALBArn
      HealthCheckEnabled: true
      UnhealthyThresholdCount: 3
      HealthCheckTimeoutSeconds: 10
      Name: !Sub ${AppShortName}-${EnvName}-${Function}-ingress-NLB-TG
      VpcId: !Ref VpcId
      HealthyThresholdCount: 3
      HealthCheckProtocol: "HTTPS"
      TargetType: "alb"
      HealthCheckPort: "traffic-port"
      Protocol: "TCP"
      Tags:
        - Key: IaCVersion
          Value: InfraPlatform-EKS-v1

  IngressNLBListener:
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]  
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      Protocol: "TCP"
      DefaultActions:
      - Type: "forward"
        ForwardConfig:
          TargetGroups:
          - TargetGroupArn: !Ref IngressNLBTG
      Port: 443
      LoadBalancerArn: !Ref IngressNLB