AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to provision an Amazon Managed Service for Prometheus (AMP) workspace and a CloudWatch Logs group for logging
Parameters:
  AppShortName:
    Type: String
    Description: AppShortName
  EnvName:
    Type: String
    Description: Environment
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-sit1
      - nprd-sit2
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b      
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - prod
      - prod-a
      - prod-b

Conditions:
  IsProduction: !Or [!Equals [!Ref "EnvName", "prod"], !Equals [!Ref "EnvName", "prod-a"], !Equals [!Ref "EnvName", "prod-b"]]

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      LogGroupName: !Sub ${AppShortName}-${EnvName}-logs-amp
      RetentionInDays: 14

  APSWorkspace:
    Type: AWS::APS::Workspace
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Alias: !Sub ${AppShortName}-${EnvName}-amp
      LoggingConfiguration:
        LogGroupArn: !GetAtt LogGroup.Arn


