{
 "title": "04-TOOLKIT - ALB",
 "tags": [
  "cloudwatch",
  "toolkit"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "loadbalancer",
    "label": "Load Balancer",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Monitoring Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Consumed LCUs",
   "type": "timeseries",
   "description": "LCU - Load balancer Capacity Units used by an Application Load Balancer\n\nAn LCU measures the dimensions on which the Application Load Balancer processes your traffic (averaged over an hour). The four dimensions measured are: New connections: Number of newly established connections per second. Typically, many requests are sent per connection.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "ConsumedLCUs",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Client TLS Negotiation Error Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "ClientTLSNegotiationErrorCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Active Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "New Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "NewConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Rejected Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "RejectedConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP Fixed Response Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTP_Fixed_Response_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP Redirect Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTP_Redirect_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP Redirect URL Limit ExceededCount",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTP_Redirect_Url_Limit_Exceeded_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode ELB 3xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode ELB 4xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode ELB 5xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Rule Evaluations",
   "type": "timeseries",
   "description": "Rule Evaluations:\nThe number of rules processed by the load balancer given a request rate averaged over an hour.\n\nReporting criteria: There is a nonzero value\n\nStatistics: The most useful statistic is Sum.\n\nDimensions: LoadBalancer",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "RuleEvaluations",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}