{
 "title": "05-TOOLKIT - API Gateway",
 "tags": [
  "cloudwatch",
  "toolkit"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "apiname",
    "label": "API Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "API Request Count",
   "type": "timeseries",
   "description": "The total number API requests in a given period. The SampleCount statistic represents this metric.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "ApiName": "$apiname" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "5XX Error",
   "type": "timeseries",
   "description": "The number of server-side errors captured in a given period. The Sum statistic represents this metric, namely, the total count of the 5XXError errors in the given period. The Average statistic represents the 5XXError error rate, namely, the total count of the 5XXError errors divided by the total number of requests during the period. The denominator corresponds to the Count metric.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "dimensions": { "ApiName": "$apiname" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "4XX Error",
   "type": "timeseries",
   "description": "The number of client-side errors captured in a given period. API Gateway counts modified gateway response status codes as 4XXError errors. The Sum statistic represents this metric, namely, the total count of the 4XXError errors in the given period. The Average statistic represents the 4XXError error rate, namely, the total count of the 4XXError errors divided by the total number of requests during the period. The denominator corresponds to the Count metric.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "dimensions": { "ApiName": "$apiname" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "The time between when API Gateway receives a request from a client and when it returns a response to the client. The latency includes the integration latency and other API Gateway overhead.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "ApiName": "$apiname" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Integration Latency",
   "type": "timeseries",
   "description": "The time difference between API Gateway sending the request to the integration and API Gateway receiving the response from the integration. Suppressed for callbacks and mock integrations with WebSocket APIs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dimensions": { "ApiName": "$apiname" },
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cache Hit Count",
   "type": "timeseries",
   "description": "The number of requests served from the API cache in a given period. The Sum statistic represents this metric, namely, the total count of the cache hits in the given period. The Average statistic represents the cache hit rate, namely, the total count of the cache hits divided by the total number of requests during the period. The denominator corresponds to the Count metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dimensions": { "ApiName": "$apiname" },
     "metricName": "CacheHitCount",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cache Miss Count",
   "type": "timeseries",
   "description": "The number of requests served from the backend in a given period, when API caching is enabled. The Sum statistic represents this metric, namely, the total count of the cache misses in the given period. The Average statistic represents the cache miss rate, namely, the total count of the cache misses divided by the total number of requests during the period. The denominator corresponds to the Count metric.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dimensions": { "ApiName": "$apiname" },
     "metricName": "CacheMissCount",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cache Hit Count vs Miss Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dimensions": { "ApiName": "$apiname" },
     "metricName": "CacheHitCount",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$apiname" },
     "metricName": "CacheMissCount",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}