{
 "title": "01-TOOLKIT - Application Health Check Monitoring",
 "tags": [
  "cloudwatch",
  "toolkit"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_cloudwatch", "query": "cloudwatch" },
   {
    "name": "apigateway",
    "label": "API Gateway",
    "query": {}
   },
   {
    "name": "apigw_loggroups",
    "label": "Log Groups",
    "query": {}
   },
   {
    "name": "api_resourcepath",
    "label": "API Resource Path",
    "query": {}
   },
   {
    "name": "period",
    "label": "Period",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Main Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2XX% API Requests",
   "type": "stat",
   "description": "Legend:\n> Green: \\>80%;\n> Yellow: \\>50%;\n> Red: <=50%;",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 40 }
   ]
  },
  {
   "title": "4XX% API Requests",
   "type": "stat",
   "description": "Legend:\n> Green: <5%;\n> Red: \\>=5%",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 40 }
   ]
  },
  {
   "title": "5XX% API Requests",
   "type": "stat",
   "description": "Legend:\n> Green: <5%;\n> Red: \\>=5%",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 40 }
   ]
  },
  {
   "title": "API Response Count",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expression": "filter @message like \"Method completed with status\"\n| parse @message \"(*) Method completed with status: *\" as MessageID, HTTP_Status\n| stats count(MessageID) as API_Count by HTTP_Status \n| sort HTTP_Status asc",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "HTTP_Status" ]
    },
    {
     "expression": "FILTER @message LIKE \"HTTP Method:\"\n| PARSE @message \"(*) HTTP Method: *, Resource Path: *\"  as API_id, Method, Resource_Path\n| FILTER Method IN [\"POST\", \"GET\"]\n| STATS COUNT(API_id) AS API_Count by API_id, Method, Resource_Path\n| SORT BY API_id, Method, Resource_Path\n| DISPLAY API_id, Method, Resource_Path, API_Count",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "API_id",
      "Method",
      "Resource_Path"
     ]
    },
    {
     "expression": "filter @message like \"Method completed with status\"\n| parse @message \"(*) Method completed with status: *\" as MessageID, HTTP_Status\n| stats COUNT(*) AS HTTP_TOTAL\n, SUM(HTTP_Status >= 200 AND HTTP_Status < 300) AS HTTP_2XX\n, SUM(HTTP_Status >= 300 AND HTTP_Status < 400) AS HTTP_3XX\n, SUM(HTTP_Status >= 400 AND HTTP_Status < 500) AS HTTP_4XX\n, SUM(HTTP_Status >= 500 AND HTTP_Status < 600) AS HTTP_5XX",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "fields status as HTTP_Status, apiKey as API_Key, latency as Latency\n| filter @message like \"httpMethod\" and not isblank(status)\n| sort @timestamp desc\n| stats count(HTTP_Status) as API_Count by HTTP_Status, API_Key, Latency\n| sort HTTP_Status asc",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "HTTP_Status",
      "API_Key",
      "Latency"
     ]
    },
    {
     "expression": "fields path as Path, status as HTTP_Status\n| filter @message like \"httpMethod\" and not isblank(status)\n| parse path \"/v1/*/\" as Endpointpath\n| sort @timestamp desc\n| stats count(HTTP_Status) as API_Count, count(*) as TotalAPI_Count by Endpointpath, Path, HTTP_Status\n| sort HTTP_Status asc",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Sum",
     "statsGroups": [
      "Endpointpath",
      "Path",
      "HTTP_Status"
     ]
    },
    {
     "expression": "fields path as Path, status as HTTP_Status\n| filter @message like \"httpMethod\" and not isblank(status)\n| parse path \"/v1/*/\" as Endpointpath\n| sort path asc\n| stats COUNT(*) AS HTTP_TOTAL\n, SUM(HTTP_Status >= 200 AND HTTP_Status < 300) AS HTTP_2XX\n, SUM(HTTP_Status >= 400 AND HTTP_Status < 500) AS HTTP_4XX\n, SUM(HTTP_Status >= 500 AND HTTP_Status < 600) AS HTTP_5XX \n, SUM(HTTP_Status >= 200 AND HTTP_Status < 300) / HTTP_TOTAL AS HTTP_2XX_Rate\n, SUM(HTTP_Status >= 400 AND HTTP_Status < 500) / HTTP_TOTAL AS HTTP_4XX_Rate\n, SUM(HTTP_Status >= 500 AND HTTP_Status < 600) / HTTP_TOTAL AS HTTP_5XX_Rate\nby Endpointpath, Path",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "Endpointpath",
      "Path"
     ]
    }
   ]
  },
  { "title": "API Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Traffic per Period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "metricEditorMode": 1,
     "metricName": "RequestCount",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "RequestCount", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(RequestCount) FROM \"AWS/ApplicationELB\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Average Integration Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "filter @message like \"Received response. Status\"\n| parse @message \"(*) Received response. Status: *, Integration latency: * ms\" as MessageID, Status, ElapsedMilliseconds\n| stats avg(ElapsedMilliseconds) as Avg_IntegrationLatency by bin($period)\n| sort Avg_IntegrationLatency desc\n| limit 1",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "metricQueryType": 1,
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Logs",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApiGateway", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "IntegrationLatency", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(IntegrationLatency) FROM \"AWS/ApiGateway\"",
     "statistic": "Average",
     "statsGroups": [ "bin($period)" ]
    }
   ]
  },
  {
   "title": "Average Integration Latency Over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ApiName": "*" },
     "expression": "filter @message like \"Received response. Status\"\n| parse @message \"(*) Received response. Status: *, Integration latency: * ms\" as MessageID, Status, IntegrationLatency\n| display MessageID, IntegrationLatency",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Logs",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApiGateway", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Route", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "AVG", "type": "function" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "IntegrationLatency", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(IntegrationLatency) FROM \"AWS/ApiGateway\" GROUP BY Route ORDER BY AVG() ASC",
     "statistic": "Average"
    },
    {
     "expression": "fields @timestamp\n| filter @message like \"HTTP Method\"\n| parse @message \"(*) HTTP Method: *, Resource Path: *\" as MessageID, HttpMethod, ResourcePath\n| sort @timestamp desc",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Maximum Integration Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "filter @message like \"Received response. Status\"\n| parse @message \"(*) Received response. Status: *, Integration latency: * ms\" as MessageID, Status, ElapsedMilliseconds\n| stats max(ElapsedMilliseconds) as Max_IntegrationLatency by bin($period)\n| sort Max_IntegrationLatency desc\n| limit 1",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "metricQueryType": 1,
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Logs",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApiGateway", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "IntegrationLatency", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT MAX(IntegrationLatency) FROM \"AWS/ApiGateway\"",
     "statistic": "Average",
     "statsGroups": [ "bin($period)" ]
    }
   ]
  },
  { "title": "Latency by API/Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Latency by API",
   "type": "timeseries",
   "description": "The time between when API Gateway receives a request from a client and when it returns a response to the client. The latency includes the integration latency and other API Gateway overhead.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/ApiGateway", "type": "functionParameter" },
        { "name": "ApiName", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "ApiName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "AVG", "type": "function" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "Latency", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(Latency) FROM SCHEMA(\"AWS/ApiGateway\", ApiName) GROUP BY ApiName ORDER BY AVG() ASC",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total API calls by Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "panelId": 61 }
   ]
  },
  {
   "title": "Average Latency by API",
   "type": "bargauge",
   "description": "The time between when API Gateway receives a request from a client and when it returns a response to the client. The latency includes the integration latency and other API Gateway overhead.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ApiName": "*" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/ApiGateway", "type": "functionParameter" },
        { "name": "ApiName", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "ApiName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "AVG", "type": "function" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "Latency", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(Latency) FROM SCHEMA(\"AWS/ApiGateway\", ApiName) GROUP BY ApiName ORDER BY AVG() ASC",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Maximum Latency by API",
   "type": "bargauge",
   "description": "The time between when API Gateway receives a request from a client and when it returns a response to the client. The latency includes the integration latency and other API Gateway overhead.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ApiName": "*" },
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/ApiGateway", "type": "functionParameter" },
        { "name": "ApiName", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "ApiName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "MAX", "type": "function" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "Latency", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT MAX(Latency) FROM SCHEMA(\"AWS/ApiGateway\", ApiName) GROUP BY ApiName ORDER BY MAX() ASC",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Statistical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "2xx by EndPoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "targets": [
    { "panelId": 61 }
   ]
  },
  {
   "title": "4xx & 5xx by API",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "targets": [
    { "panelId": 61 }
   ]
  },
  {
   "title": "API Success and Failure rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "targets": [
    { "panelId": 63 }
   ]
  },
  {
   "title": "API Success Over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expression": "filter @message like \"Method completed with status\"\n| parse @message \"(*) Method completed with status: *\" as MessageID, Status\n| filter ispresent(Status) and (Status >= 200 and Status < 300)\n| stats count(Status) as Requests by bin($period)",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin($period)" ]
    }
   ]
  },
  {
   "title": "4XX Failure Over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "expression": "filter @message like \"Method completed with status\"\n| parse @message \"(*) Method completed with status: *\" as MessageID, Status\n| filter ispresent(Status) and (Status >= 400 and Status < 500)\n| stats count(Status) as Requests by bin($period)",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin($period)" ]
    }
   ]
  },
  {
   "title": "5XX Failure Over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expression": "filter @message like \"Method completed with status\"\n| parse @message \"(*) Method completed with status: *\" as MessageID, Status\n| filter ispresent(Status) and (Status >= 500 and Status < 600)\n| stats count(Status) as Requests by bin($period)",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin($period)" ]
    }
   ]
  },
  {
   "title": "% Utilization by API",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 61 }
   ]
  },
  {
   "title": "Utilization by API",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 57 },
   "targets": [
    { "panelId": 61 }
   ]
  },
  { "title": "Log Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Table API Status, httpMethod, & ResourcePath",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expression": "fields @timestamp\n| filter @message like \"Method completed with status\"\n| parse @message \"(*) Method completed with status: *\" as MessageID, Status\n| sort @timestamp desc",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "fields @timestamp\n| filter @message like \"HTTP Method\"\n| parse @message \"(*) HTTP Method: *, Resource Path: *\" as MessageID, HttpMethod, ResourcePath\n| sort @timestamp desc",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Table API Breakdown Status, & ResourcePath",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expression": "filter @message like \"Method completed with status\"\n| parse @message \"(*) Method completed with status: *\" as MessageID, HTTP_Status\n| stats COUNT(*) AS HTTP_TOTAL\n, SUM(HTTP_Status >= 200 AND HTTP_Status < 300) AS HTTP_2XX\n, SUM(HTTP_Status >= 300 AND HTTP_Status < 400) AS HTTP_3XX\n, SUM(HTTP_Status >= 400 AND HTTP_Status < 500) AS HTTP_4XX\n, SUM(HTTP_Status >= 500 AND HTTP_Status < 600) AS HTTP_5XX\nby MessageID, HTTP_Status",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "MessageID",
      "HTTP_Status"
     ]
    },
    {
     "expression": "fields @timestamp\n| filter @message like \"HTTP Method\"\n| parse @message \"(*) HTTP Method: *, Resource Path: *\" as MessageID, HttpMethod, ResourcePath\n| sort @timestamp desc",
     "logGroups": [
      { "arn": "$apigw_loggroups", "name": "$apigw_loggroups" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}