{
 "title": "03-TOOLKIT-ECS",
 "tags": [
  "cloudwatch",
  "toolkit"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   { "name": "period", "label": "Period [sec]", "query": "1m,3m,5m" }
  ]
 },
 "panels": [
  { "title": "Instance, Task, & Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task Count",
   "type": "stat",
   "description": "TaskCount\n\nThe number of tasks running in the cluster.\n\n\nMeaningful Statistics: Average, Minimum, Maximum, Sum\n\nUnit info: Count",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "TaskCount",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Service Count",
   "type": "stat",
   "description": "ServiceCount\n\nThe number of services in the cluster.\n\n\nMeaningful Statistics: Average, Minimum, Maximum\n\nUnit info: Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "ServiceCount",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Running Task",
   "type": "stat",
   "description": "TaskCount\n\nThe number of tasks running in the cluster.\n\n\nMeaningful Statistics: Average, Minimum, Maximum, Sum\n\nUnit info: Count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "description": "Calculated as =\n(CPU Utilized * 100%) /  CPU Reserved",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expression": "($A * 100) / $B", "type": "math" }
   ]
  },
  {
   "title": "CPU Reserved",
   "type": "timeseries",
   "description": "CPUReserved\n\nThe CPU units reserved by tasks in the resource that is specified by the dimension set that you're using. This metric is collected only for tasks that have a defined CPU reservation in their task definition.\n\n\nMeaningful Statistics: Average, Minimum, Maximum\n\nUnit info: None",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "CpuReserved",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilized",
   "type": "timeseries",
   "description": "CPUUtilized\n\nThe CPU units used by tasks in the resource that is specified by the dimension set that you're using. This metric is collected only for tasks that have a defined CPU reservation in their task definition.\n\n\nMeaningful Statistics: Average, Minimum, Maximum\n\nUnit info: None",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "description": "Calculated as = \n(Memory Utilized * 100%) /  Memory Reserved",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    { "expression": "($A * 100) / $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Reserved",
   "type": "timeseries",
   "description": "MemoryReserved\n\nThe memory that is reserved by tasks in the resource that is specified by the dimension set that you're using. This metric is collected only for tasks that have a defined memory reservation in their task definition.\n\n\nMeaningful Statistics: Average, Minimum, Maximum\n\nUnit info: Megabytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "MemoryReserved",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory Utilized",
   "type": "timeseries",
   "description": "MemoryUtilized\n\nThe memory being used by tasks in the resource that is specified by the dimension set that you're using. This metric is collected only for tasks that have a defined memory reservation in their task definition.\n\n\nMeaningful Statistics: Average, Minimum, Maximum\n\nUnit info: Megabytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Network Utilization (Total)",
   "type": "timeseries",
   "description": "Calculated as = \n(Network Received Bytes + Network Transmitted Bytes)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Network Received Bytes",
   "type": "timeseries",
   "description": "NetworkRxBytes\n\nThe number of bytes received by the resource that is specified by the dimensions that you're using. This metric is obtained from the Docker runtime. This metric is available only for containers in tasks using the awsvpc or bridge network modes.\n\n\nMeaningful Statistics: Average, Minimum, Maximum, Sum\n\nUnit info: Bytes/Second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Transmitted Bytes",
   "type": "timeseries",
   "description": "NetworkTxBytes\n\nThe number of bytes transmitted by the resource that is specified by the dimensions that you're using. This metric is obtained from the Docker runtime. This metric is available only for containers in tasks using the awsvpc or bridge network modes.\n\n\nMeaningful Statistics: Average, Minimum, Maximum, Sum\n\nUnit info: Bytes/Second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Disk Utilization (%)",
   "type": "timeseries",
   "description": "Calculated as =\n(EphemeralStorageUtilized * 100%) /  EphemeralStorageReserved",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expression": "SELECT SUM(EphemeralStorageUtilized) FROM SCHEMA(\"ECS/ContainerInsights\", ClusterName) GROUP BY ClusterName",
     "metricEditorMode": 1,
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "ECS/ContainerInsights", "type": "functionParameter" },
        { "name": "ClusterName", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "ClusterName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "CpuUtilized", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "statistic": "Sum"
    },
    {
     "expression": "SELECT SUM(EphemeralStorageReserved) FROM SCHEMA(\"ECS/ContainerInsights\", ClusterName) GROUP BY ClusterName",
     "metricEditorMode": 1,
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "ECS/ContainerInsights", "type": "functionParameter" },
        { "name": "ClusterName", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "ClusterName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "CpuUtilized", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "statistic": "Sum"
    },
    { "expression": "($A/$B)", "type": "math" }
   ]
  },
  {
   "title": "Storage Utilized (GB)",
   "type": "timeseries",
   "description": "EphemeralStorageUtilized\n\nThe number of bytes used from ephemeral storage in the resource that is specified by the dimensions that you're using. Ephemeral storage is used for the container root filesystem and any bind mount host volumes defined in the container image and task definition. The amount of ephemeral storage can’t be changed in a running task. This metric is only available for tasks that run on Fargate Linux platform version 1.4.0 or later.\n\nMeaningful Statistics: Average, Minimum, Maximum\n\nUnit info: Gigabytes (GB)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "expression": "SELECT SUM(EphemeralStorageUtilized) FROM SCHEMA(\"ECS/ContainerInsights\", ClusterName) GROUP BY ClusterName",
     "metricEditorMode": 1,
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Storage Reserved (GB)",
   "type": "timeseries",
   "description": "EphemeralStorageReserved\n\nThe number of bytes reserved from ephemeral storage in the resource that is specified by the dimensions that you're using. Ephemeral storage is used for the container root filesystem and any bind mount host volumes defined in the container image and task definition. The amount of ephemeral storage can’t be changed in a running task. This metric is only available for tasks that run on Fargate Linux platform version 1.4.0 or later.\n\nMeaningful Statistics: Average, Minimum, Maximum\n\nUnit info: Gigabytes (GB)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "expression": "SELECT SUM(EphemeralStorageReserved) FROM SCHEMA(\"ECS/ContainerInsights\", ClusterName) GROUP BY ClusterName",
     "metricEditorMode": 1,
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    }
   ]
  }
 ]
}