{
 "title": "AWS ElastiCache Redis",
 "description": "Visualize AWS ElastiCache Redis metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "cacheclusterId",
    "label": "CacheClusterId",
    "query": "dimension_values($region,AWS/ElastiCache,CPUUtilization,CacheClusterId)"
   },
   {
    "name": "cachenodeid",
    "label": "CacheNodeId",
    "query": "dimension_values($region,AWS/ElastiCache,CPUUtilization,CacheNodeId)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPUUtilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "period": "1m",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Engine CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "metricName": "EngineCPUUtilization",
     "namespace": "AWS/ElastiCache",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cache Performance Overview",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Evictions",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Reclaimed",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NewConnections",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "FreeableMemory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SwapUsage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SwapUsage",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Engine CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Engine CPU Utilization",
   "type": "timeseries",
   "description": "Redis Server CPU Usage",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "metricName": "EngineCPUUtilization",
     "namespace": "AWS/ElastiCache",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cmds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "GetTypeCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HashBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ListBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SetBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SetTypeCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SortedSetBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "StringBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "StreamBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SaveInProgress / CurrItems",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SaveInProgress",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CurrItems",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesUsedForCache / ReplicationBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReplicationBytes",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "StreamBasedCmdsLatency / ReplicationLag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "StreamBasedCmdsLatency",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReplicationLag",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid DatabaseMemoryUsagePercentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid NetworkBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}