{
 "title": "02-TOOLKIT - RDS",
 "tags": [
  "cloudwatch",
  "toolkit"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   { "name": "period", "label": "Period [sec]", "query": "60,180,300" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization - Maximum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Freeable Memory - Maximum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Login Failure Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "LoginFailures",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Database connections [count sum]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Dead Lock Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "Deadlocks",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Available storage space [bytes]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU utilization per instance [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Available RAM [bytes]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Instance metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read throughput [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write throughput [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read latency [sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Write latency [sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Read operations [IOPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write operations [IOPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
     "options": {
      "content": "For more information about the available Amazon RDS metrics, please visit the [Amazon RDS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MonitoringOverview.html#rds-metrics)."
     },
     "targets": [
      { "region": "default", "statistic": "Average" }
     ]
    }
   ]
  }
 ]
}