AWSTemplateFormatVersion: 2010-09-09
Description: AWS S3 Buckets Template

Parameters:
  AppShortName:
    Type: String
    Description: AppShortName

  EnvName:
    Type: String
    Description: Environment
    AllowedValues:
      - nprd
      - prod
      - nprd-dev
      - nprd-sit1
      - nprd-sit2
      - nprd-uat
      - nprd-pt

Conditions:
  IsProduction: !Equals
    - !Ref EnvName
    - prod

Resources:  
  AppArtefactS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: !Sub ${AppShortName}-${EnvName}-app-artefact
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AppArtefactS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Bucket: !Ref AppArtefactS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceTLSv12orHigher
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt AppArtefactS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt AppArtefactS3Bucket.Arn
                    - '/*'
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Resource: 
              - !GetAtt AppArtefactS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt AppArtefactS3Bucket.Arn
                    - '/*'
            Principal: '*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  AppRuntimeS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: !Sub ${AppShortName}-${EnvName}-app-runtime
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true       

  AppRuntimeS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Bucket: !Ref AppRuntimeS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceTLSv12orHigher
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt AppRuntimeS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt AppRuntimeS3Bucket.Arn
                    - '/*'
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Resource: 
              - !GetAtt AppRuntimeS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt AppRuntimeS3Bucket.Arn
                    - '/*'
            Principal: '*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  AppS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: !Sub ${AppShortName}-${EnvName}-app
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AppS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Bucket: !Ref AppS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceTLSv12orHigher
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt AppS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt AppS3Bucket.Arn
                    - '/*'
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Resource: 
              - !GetAtt AppS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt AppS3Bucket.Arn
                    - '/*'
            Principal: '*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  DataloadS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: !Sub ${AppShortName}-${EnvName}-dataload
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DataloadS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Bucket: !Ref DataloadS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceTLSv12orHigher
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt DataloadS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt DataloadS3Bucket.Arn
                    - '/*'
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Resource: 
              - !GetAtt DataloadS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt DataloadS3Bucket.Arn
                    - '/*'
            Principal: '*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  DataExtractionS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: !Sub ${AppShortName}-${EnvName}-data-extraction
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DataExtractionS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Bucket: !Ref DataExtractionS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceTLSv12orHigher
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt DataExtractionS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt DataExtractionS3Bucket.Arn
                    - '/*'
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Resource: 
              - !GetAtt DataExtractionS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt DataExtractionS3Bucket.Arn
                    - '/*'
            Principal: '*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  ec2UploadS3Bucket:    # s3 bucket to transfer the installer files from office laptop to ec2 instances
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: !Sub ${AppShortName}-${EnvName}-ec2-upload
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ec2UploadS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ec2UploadS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceTLSv12orHigher
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt ec2UploadS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt ec2UploadS3Bucket.Arn
                    - '/*'
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Resource: 
              - !GetAtt ec2UploadS3Bucket.Arn
              - !Join
                  - ''
                  - - !GetAtt ec2UploadS3Bucket.Arn
                    - '/*'
            Principal: '*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'