AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Security Group Conditional Creation based on user choice v6
Parameters:
  AppShortName:
    Type: String
    Description: AppShortName
  EnvName:
    Type: String
    Description: Environment
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-dev1
      - nprd-dev2
      - nprd-sit1
      - nprd-sit2
      - nprd-sit3
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-sit-c
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b
      - nprd-uat-c
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - nprd-pp-c
      - prod
      - prod-a
      - prod-b
      - prod-c
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  CreateAppSecurityGroup:
    Type: String
    Description: Do you want to create the App Security Group? (yes/no)
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'yes'
  CreateDeploymentSecurityGroup:
    Type: String
    Description: Do you want to create the Deployment Security Group? (yes/no)
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'no'
  ALBSecurityGroupId:
    Type: String
    Description: Application Load Balancer Security Group id
  AnsibleServerIP1:
    Type: String
    Description: IP Address of the first Ansible server in x.x.x.x/32 format
  AnsibleServerIP2:
    Type: String
    Description: IP Address of the second Ansible server in x.x.x.x/32 format
  EC2AppSecurityGroupName:
    Type: String
    Description: Name for the EC2 App Security Group
  EC2DeploymentSecurityGroupName:
    Type: String
    Description: Name for the EC2 Deployment Security Group

  VPCSubnetCidrDBAZ1:
    Type: String
    Description: AZ1 DB Subnet
  
  VPCSubnetCidrDBAZ2:
    Type: String
    Description: AZ2 DB Subnet

  VPCSubnetCidrDBAZ3:
    Type: String
    Description: AZ3 DB Subnet

  ProdDBPort:
    Type: String
    Default: 53341
    NoEcho: true

  NProdDBPort:
    Type: String
    Default: 53331
    NoEcho: true
    
Conditions:
  IsProduction: !Or [!Equals [!Ref "EnvName", "prod"], !Equals [!Ref "EnvName", "prod-a"], !Equals [!Ref "EnvName", "prod-b"], !Equals [!Ref "EnvName", "prod-c"]]
  ShouldCreateAppSecurityGroup: !Equals [!Ref CreateAppSecurityGroup, 'yes']
  ShouldCreateDeploymentSecurityGroup: !Equals [!Ref CreateDeploymentSecurityGroup, 'yes']
  HasALBSecurityGroup: !Not [!Equals [!Ref ALBSecurityGroupId, ""]]
  HasAnsibleServerIP1: !Not [!Equals [!Ref AnsibleServerIP1, ""]]
  HasAnsibleServerIP2: !Not [!Equals [!Ref AnsibleServerIP2, ""]]
  HasVPCSubnetCidrDBAZ3: !Not [!Equals [!Ref VPCSubnetCidrDBAZ3, '']]

Resources:
  EC2AppSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Condition: ShouldCreateAppSecurityGroup
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      GroupDescription: Common Security Group for EC2
      GroupName: !Ref EC2AppSecurityGroupName
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - !If 
            - HasALBSecurityGroup
            - 
              IpProtocol: tcp
              FromPort: 443
              ToPort: 443
              SourceSecurityGroupId: !Ref ALBSecurityGroupId
              Description: Application Load Balancer SecurityGroup ID
            - !Ref AWS::NoValue
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          CidrIp: !Ref VPCSubnetCidrDBAZ1
          Description: Allow DB AZ1 Subnet
        - IpProtocol: tcp
          FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          CidrIp: !Ref VPCSubnetCidrDBAZ2
          Description: Allow DB AZ2 Subnet
        - !If
          - HasVPCSubnetCidrDBAZ3
          - IpProtocol: tcp
            FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
            ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
            CidrIp: !Ref VPCSubnetCidrDBAZ3
            Description: Allow DB Subnet AZ3
          - !Ref "AWS::NoValue"
      Tags:
        - Key: IaCVersion
          Value: InfraPlatform-EC2-v6

  EC2DeploymentSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Condition: ShouldCreateDeploymentSecurityGroup
    Properties:
      GroupDescription: Deployment Security Group for EC2
      GroupName: !Ref EC2DeploymentSecurityGroupName
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5986
          ToPort: 5986
          CidrIp: !If [HasAnsibleServerIP1, !Ref AnsibleServerIP1, !Ref "AWS::NoValue"]
          Description: Access from Ansible Server 1
        - IpProtocol: tcp
          FromPort: 5986
          ToPort: 5986
          CidrIp: !If [HasAnsibleServerIP2, !Ref AnsibleServerIP2, !Ref "AWS::NoValue"]
          Description: Access from Ansible Server 2
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          CidrIp: !Ref VPCSubnetCidrDBAZ1
          Description: Allow DB AZ1 Subnet
        - IpProtocol: tcp
          FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          CidrIp: !Ref VPCSubnetCidrDBAZ2
          Description: Allow DB AZ2 Subnet
        - !If
          - HasVPCSubnetCidrDBAZ3
          - IpProtocol: tcp
            FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
            ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
            CidrIp: !Ref VPCSubnetCidrDBAZ3
            Description: Allow DB Subnet AZ3
          - !Ref "AWS::NoValue"    
      Tags:
        - Key: IaCVersion
          Value: InfraPlatform-EC2-v6