AWSTemplateFormatVersion: 2010-09-09
Description: RDS Read Replica V3
Parameters:

  AppShortName:
    Type: String
    Description: AppShortName

  EnvName:
    Type: String
    Description: Environment
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-sit1
      - nprd-sit2
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b      
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - prod
      - prod-a
      - prod-b
      
  ReadReplicaRdsDBParameterGroupFamily:
    Type: String
    Description: Parameter group family

  DBEngine:
    Type: String
    Description: Enter the SQL DB Engine version, se is standard and ee is enterprise
    AllowedValues:
      - sqlserver-se
      - sqlserver-ee

  ReadReplicaDBInstanceClass:
    Type: String
    Description: The database instance type

Conditions:
  IsProduction: !Equals
    - !Ref EnvName
    - prod

Resources:

  ReadReplicaRdsDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      DBParameterGroupName: !Sub '${AppShortName}-${EnvName}-ReadReplica-sqlserver-ee-ParameterGroup'
      Description: '${AppShortName}-${EnvName}-ReadReplica-sqlserver-ee-ParameterGroup'
      Family: !Ref ReadReplicaRdsDBParameterGroupFamily

  ReplicaDB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]  
    Properties:
      SourceDBInstanceIdentifier: !Sub '{{resolve:ssm:${AppShortName}-${EnvName}-parameter-RDSInstanceName}}'
      DBInstanceIdentifier: !Sub '${AppShortName}-${EnvName}-readreplica-rdssql'
      DBParameterGroupName: !Ref ReadReplicaRdsDBParameterGroup
      DBInstanceClass: !Ref ReadReplicaDBInstanceClass
      EnablePerformanceInsights: true
      MonitoringInterval: 60
      MonitoringRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${AppShortName}-${EnvName}-rds-EnhancedMonitoring-Role
      DeletionProtection: true
      EnableCloudwatchLogsExports:
      - "agent"
      - "error"
      CopyTagsToSnapshot: true
      Tags:
        - Key: BACKUP-DAILY
          Value: 'YES'
        - Key: BACKUP-WEEKLY
          Value: 'YES'
        - Key: BACKUP-MONTHLY
          Value: 'YES'
        - Key: BACKUP-YEARLY
          Value: 'YES'
        - Key: BACKUP-CONTINOUS
          Value: 'YES'