AWSTemplateFormatVersion: 2010-09-09
## VPC-id, Subnets ID, ClusterSharedNodeSecurityGroup name, Cluser Control Plane name and Control Plane SecurityGroup name to be updated as per requirements.
Description: EC2 Launch Template
Parameters:
  AppShortName:
    Type: String
    Description: AppShortName
  EnvName:
    Type: String
    Description: Environment
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-sit1
      - nprd-sit2
      - nprd-uat
      - nprd-pt
      - prod
  Function:
    Type: String
    Description: Server Function (eg, APP, UTL, DB)
    AllowedValues:
      - APP
      - WEB
      - DB
      - UTL

Resources:
  EC2IAMRole:
    Type: 'AWS::IAM::Role'
#    DeletionPolicy: Retain
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      RoleName: !Sub ${AppShortName}-${EnvName}-ec2-${Function}-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub ${AppShortName}-${EnvName}-ec2-${Function}-profile
      Roles: 
        - !Ref EC2IAMRole

  EC2KeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: !Sub ${AppShortName}-${EnvName}-EC2-${Function}-KeyPair

  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DependsOn: 
      - EC2IAMRole
    Properties: 
      LaunchTemplateName: !Sub ${AppShortName}-${EnvName}-ec2-lt-${Function}
      LaunchTemplateData:
#        IamInstanceProfile:
#          Arn: !GetAtt EC2InstanceProfile.Arn
        KeyName: !Ref EC2KeyPair
        TagSpecifications:
          - ResourceType: instance
            Tags: 
              - Key: FUNCTION
                Value: !Ref Function
              - Key: OPERATING-SYSTEM
                Value: WIN      
              - Key: EBS-SNAPSHOT
                Value: 'YES'
              - Key: Name
                Value: !Sub ${AppShortName}-${EnvName}-EC2
              - Key: BACKUP-DAILY
                Value: 'YES'
              - Key: BACKUP-WEEKLY
                Value: 'YES'
              - Key: CW-CONFIG
                Value: 'BASELINE'
              - Key: CREATE-AUTO-ALARMS
                Value: ''
          - ResourceType: volume
            Tags: 
              - Key: FUNCTION
                Value: !Ref Function
              - Key: OPERATING-SYSTEM
                Value: WIN      
              - Key: EBS-SNAPSHOT
                Value: 'YES'
              - Key: Name
                Value: !Sub ${AppShortName}-${EnvName}-EBS
          - ResourceType: network-interface
            Tags: 
              - Key: FUNCTION
                Value: !Ref Function
              - Key: OPERATING-SYSTEM
                Value: WIN      
              - Key: EBS-SNAPSHOT
                Value: 'YES'
              - Key: Name
                Value: !Sub ${AppShortName}-${EnvName}-vNIC

Outputs:
  EC2LaunchTemplateID:
    Description: The ID of EC2 LaunchTemplate
    Value: !Ref EC2LaunchTemplate
    Export:
      Name: "EC2LaunchTemplateID"
  EC2LaunchTemplateLatestVersionNumber:
    Description: EC2LaunchTemplate Latest Version Number
    Value: !GetAtt EC2LaunchTemplate.LatestVersionNumber
    Export:
      Name: "EC2LaunchTemplateLatestVersionNumber"
  EC2InstanceProfileName:
    Description: EC2 Instance Profile Name
    Value: !Ref EC2InstanceProfile
    Export:
      Name: "EC2InstanceProfileName"
  EC2InstanceProfileArn:
    Description: EC2 Instance Profile Arn
    Value: !GetAtt EC2InstanceProfile.Arn
    Export:
      Name: "EC2InstanceProfileArn"  