AWSTemplateFormatVersion: 2010-09-09
## Provisioning of EC2
Description: EC2
Parameters:
  AppShortName:
    Type: String
    Description: AppShortName
  EnvName:
    Type: String
    Description: Environment
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-sit1
      - nprd-sit2
      - nprd-uat
      - nprd-pt
      - prod
  VpcId:
    Type: String
    Description: VPC ID
  Function:
    Type: String
    Description: Server Function (eg, APP, UTL, DB)
    AllowedValues:
      - APP
      - RP
      - WEB
      - DB
      - UTL
  ALBSecurityGroupId:
    Type: String
    Description: Application Locad Balancer Security Group id
  VpcCidr1:
    Description: VPC CIDR 1 IP Range
    Type: String
    Default: ""
  VpcCidr2:
    Description: VPC CIDR 2 IP Range
    Type: String
    Default: ""
  VpcCidr3:
    Description: VPC CIDR 3 IP Range
    Type: String
    Default: ""
  S3PrefixListId:
    Description: S3 PrefixList ID
    Type: String
    Default: ""
  HCCVpceCidr:
    Description: HCC VPC Endpoint Subnet, Fixed CIDR Range from HCC
    Type: String
    Default: ""
  AnsibleServerIP1:
    Type: String
    Description: IP Address of the first Ansible server in x.x.x.x/32 format
  AnsibleServerIP2:
    Type: String
    Description: IP Address of the second Ansible server in x.x.x.x/32 format
  EC2AppSecurityGroupName:
    Type: String
    Description: Name for the EC2 App Security Group
  EC2DeploymentSecurityGroupName:
    Type: String
    Description: Name for the EC2 Deployment Security Group

  VPCSubnetCidrDBAZ1:
    Type: String
    Description: AZ1 DB Subnet
  
  VPCSubnetCidrDBAZ2:
    Type: String
    Description: AZ2 DB Subnet

  VPCSubnetCidrDBAZ3:
    Type: String
    Description: AZ3 DB Subnet

  ProdDBPort:
    Type: String
    Default: 53341
    NoEcho: true

  NProdDBPort:
    Type: String
    Default: 53331
    NoEcho: true

Conditions:
  IsProduction: !Equals
    - !Ref EnvName
    - prod
  HasALBSecurityGroup: !Not [!Equals [!Ref ALBSecurityGroupId, '']]
  HasVpcCidr3: !Not [!Equals [!Ref VpcCidr3, ""]]
  HasVpcCidr2: !Not [!Equals [!Ref VpcCidr2, ""]]
  HasHCCVpceCidr: !Not [!Equals [!Ref HCCVpceCidr, ""]]
  HasS3PrefixListId: !Not [!Equals [!Ref S3PrefixListId, ""]]
  HasAnsibleServerIP1: !Not [!Equals [!Ref AnsibleServerIP1, ""]]
  HasAnsibleServerIP2: !Not [!Equals [!Ref AnsibleServerIP2, ""]]
  HasVPCSubnetCidrDBAZ3: !Not [!Equals [!Ref VPCSubnetCidrDBAZ3, '']]

Resources:
  EC2InfraSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]  
    Properties:
      GroupDescription: Common Infra Security Group for EC2
      GroupName:  !Sub sg_${AppShortName}-${EnvName}-ec2-infra
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr1
          Description: VPC CIDR 1 IP Range
        - !If 
          - HasVpcCidr2
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: !Ref VpcCidr2
            Description: VPC CIDR 2 IP Range
          - !Ref "AWS::NoValue"
        - !If
          - HasVpcCidr3
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: !Ref VpcCidr3
            Description: VPC CIDR 3 IP Range
          - !Ref "AWS::NoValue"     
        - !If
          - HasS3PrefixListId
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            DestinationPrefixListId: !Ref S3PrefixListId
            Description: Allow access to Amazon S3 Endpoint
          - !Ref "AWS::NoValue"
        - !If
          - HasHCCVpceCidr
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: !Ref HCCVpceCidr
            Description: HCC VPC Endpoint Subnet
          - !Ref "AWS::NoValue"

#      SecurityGroupIngress:
  EC2AppSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      GroupDescription: Common Security Group for EC2
      GroupName:  !Sub sg_${AppShortName}-${EnvName}-ec2-${Function}
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - !If 
            - "HasALBSecurityGroup"
            - IpProtocol: tcp
              FromPort: 443
              ToPort: 443
              SourceSecurityGroupId: !Ref ALBSecurityGroupId
              Description: ApplicationLoadBalancer SecurityGroup ID
            - !Ref AWS::NoValue
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          CidrIp: !Ref VPCSubnetCidrDBAZ1
          Description: Allow DB AZ1 Subnet
        - IpProtocol: tcp
          FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          CidrIp: !Ref VPCSubnetCidrDBAZ2
          Description: Allow DB AZ2 Subnet
        - !If
          - HasVPCSubnetCidrDBAZ3
          - IpProtocol: tcp
            FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
            ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
            CidrIp: !Ref VPCSubnetCidrDBAZ3
            Description: Allow DB Subnet AZ3
          - !Ref "AWS::NoValue" 
        - IpProtocol: tcp
          FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          CidrIp: !Ref VPCSubnetCidrDBAZ1
          Description: Allow DB AZ1 Subnet
        - IpProtocol: tcp
          FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
          CidrIp: !Ref VPCSubnetCidrDBAZ2
          Description: Allow DB AZ2 Subnet
        - !If
          - HasVPCSubnetCidrDBAZ3
          - IpProtocol: tcp
            FromPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
            ToPort: !If [IsProduction, !Ref ProdDBPort, !Ref NProdDBPort]
            CidrIp: !Ref VPCSubnetCidrDBAZ3
            Description: Allow DB Subnet AZ3
          - !Ref "AWS::NoValue"

Outputs:
  EC2InfraSecurityGroupID:
    Description: EC2 Infra Security Group ID
    Value: !GetAtt EC2InfraSecurityGroup.GroupId
    Export:
      Name: "EC2InfraSecurityGroupID"
  EC2AppSecurityGroupID:
    Description: EC2 App Security Group ID
    Value: !GetAtt EC2AppSecurityGroup.GroupId
    Export:
      Name: "EC2AppSecurityGroupID"