AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Launch Template

Parameters:
  AppShortName:
    Type: String
    Description: AppShortName
  EnvName:
    Type: String
    Description: Environment
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-sit1
      - nprd-sit2
      - nprd-sit3
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-sit-c
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b
      - nprd-uat-c
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - nprd-pp-c
      - prod
      - prod-a
      - prod-b
      - prod-c
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  EC2IAMRoleName:
    Type: String
    Description: Name for the EC2 IAM Role
  EC2InstanceProfileName:
    Type: String
    Description: Name for the EC2 Instance Profile
  EC2KeyPairName:
    Type: String
    Description: Name for the EC2 Key Pair
  EC2LaunchTemplateName:
    Type: String
    Description: Name for the EC2 Launch Template
  EC2InfraSecurityGroupName:
    Type: String
    Description: Name for the EC2 Infra Security Group

Conditions:
  IsProduction: !Or [!Equals [!Ref "EnvName", "prod"], !Equals [!Ref "EnvName", "prod-a"], !Equals [!Ref "EnvName", "prod-b"], !Equals [!Ref "EnvName", "prod-c"]]

Resources:
  EC2IAMRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      RoleName: !Ref EC2IAMRoleName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Tags:
        - Key: IaCVersion
          Value: InfraPlatform-EC2-v4

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties: 
      InstanceProfileName: !Ref EC2InstanceProfileName
      Roles: 
        - !Ref EC2IAMRole

  EC2KeyPair:
    Type: 'AWS::EC2::KeyPair'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      KeyName: !Ref EC2KeyPairName
      Tags:
        - Key: IaCVersion
          Value: InfraPlatform-EC2-v4

  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    DependsOn: 
      - EC2IAMRole
    Properties: 
      LaunchTemplateName: !Ref EC2LaunchTemplateName
      LaunchTemplateData:
        KeyName: !Ref EC2KeyPair
        MetadataOptions:
          HttpTokens: required
        TagSpecifications:
          - ResourceType: instance
            Tags: 
              - Key: FUNCTION
                Value: TBC
              - Key: EBS-SNAPSHOT
                Value: 'YES'
              - Key: Name
                Value: !Sub ${AppShortName}-${EnvName}-EC2
              - Key: BACKUP-DAILY
                Value: 'YES'
              - Key: BACKUP-WEEKLY
                Value: 'YES'
              - Key: BACKUP-MONTHLY
                Value: 'YES'
              - Key: BACKUP-YEARLY
                Value: 'YES'
              - Key: CW-CONFIG
                Value: 'BASELINE'
              - Key: CREATE-AUTO-ALARMS
                Value: ''
              - Key: IaCVersion
                Value: InfraPlatform-EC2-v4
          - ResourceType: volume
            Tags: 
              - Key: FUNCTION
                Value: TBC
              - Key: EBS-SNAPSHOT
                Value: 'YES'
              - Key: Name
                Value: !Sub ${AppShortName}-${EnvName}-EBS
              - Key: BACKUP-DAILY
                Value: 'YES'
              - Key: BACKUP-WEEKLY
                Value: 'YES'
              - Key: BACKUP-MONTHLY
                Value: 'YES'
              - Key: BACKUP-YEARLY
                Value: 'YES'
              - Key: IaCVersion
                Value: InfraPlatform-EC2-v4
          - ResourceType: network-interface
            Tags: 
              - Key: FUNCTION
                Value: TBC
              - Key: Name
                Value: !Sub ${AppShortName}-${EnvName}-vNIC
              - Key: IaCVersion
                Value: InfraPlatform-EC2-v4
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: IaCVersion
              Value: InfraPlatform-EC2-v4

  EC2InfraSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]  
    Properties:
      GroupDescription: Common Infra Security Group for EC2
      GroupName: !Ref EC2InfraSecurityGroupName
      VpcId: !Ref VpcId
      Tags:
        - Key: IaCVersion
          Value: InfraPlatform-EC2-v4

# Parameters will be referenced by EC2 template 
  ParameterEC2LTID: #Parameter for EC2 Launch Template ID
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${AppShortName}-${EnvName}-parameter-EC2LaunchTemplateID
      Description: !Sub ${AppShortName}-${EnvName}-parameter-EC2LaunchTemplateID
      Value: !Ref EC2LaunchTemplate
      Type: String
      Tier: Standard
      Tags:
        IaCVersion: InfraPlatform-EC2-v4

  ParameterEC2LTLatestVNum: #Parameter for EC2 Launch Template Latest Version Number
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${AppShortName}-${EnvName}-parameter-EC2LaunchTemplateLatestVersionNumber
      Description: !Sub ${AppShortName}-${EnvName}-parameter-EC2LaunchTemplateLatestVersionNumber
      Value: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      Type: String
      Tier: Standard
      Tags:
        IaCVersion: InfraPlatform-EC2-v4

  ParameterEC2InstanceProfileName: #Parameter for EC2 Instance Profile Name
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${AppShortName}-${EnvName}-parameter-EC2InstanceProfileName
      Description: !Sub ${AppShortName}-${EnvName}-parameter-EC2InstanceProfileName
      Value: !Ref EC2InstanceProfile
      Type: String
      Tier: Standard
      Tags:
        IaCVersion: InfraPlatform-EC2-v4