AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Secrets Configuration v5.0

Parameters:
  AppShortName:
    Type: String
    Description: AppShortName
  EnvName:
    Type: String
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-dev1
      - nprd-dev2
      - nprd-sit1
      - nprd-sit2
      - nprd-sit3
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-sit-c
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b
      - nprd-uat-c      
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - nprd-pp-c
      - prod
      - prod-a
      - prod-b
      - prod-c
    Description: Environment

Conditions:
  IsProduction: !Or [!Equals [!Ref "EnvName", "prod"], !Equals [!Ref "EnvName", "prod-a"], !Equals [!Ref "EnvName", "prod-b"], !Equals [!Ref "EnvName", "prod-c"]]
  HasSubEnvironmentNprd: !Or 
    - !Equals [!Ref "EnvName", "nprd-sit-a"]
    - !Equals [!Ref "EnvName", "nprd-sit-b"]
    - !Equals [!Ref "EnvName", "nprd-sit-c"]
    - !Equals [!Ref "EnvName", "nprd-uat-a"]
    - !Equals [!Ref "EnvName", "nprd-uat-b"]
    - !Equals [!Ref "EnvName", "nprd-uat-c"]
    - !Equals [!Ref "EnvName", "nprd-pp-a"]
    - !Equals [!Ref "EnvName", "nprd-pp-b"]
    - !Equals [!Ref "EnvName", "nprd-pp-c"]
  HasSubEnvironmentProd: !Or 
    - !Equals [!Ref "EnvName", "prod-a"]
    - !Equals [!Ref "EnvName", "prod-b"]
    - !Equals [!Ref "EnvName", "prod-c"]
  HasSubEnvironment: !Or 
    - !Condition HasSubEnvironmentNprd
    - !Condition HasSubEnvironmentProd

Mappings: 
  EnvironmentMap: 
    prod: { ParentEnv: "prod" } 
    prod-a: { ParentEnv: "prod" } 
    prod-b: { ParentEnv: "prod" }
    prod-c: { ParentEnv: "prod" }
    nprd: { ParentEnv: "nprd" } 
    nprd-dev: { ParentEnv: "nprd-dev" } 
    nprd-sit: { ParentEnv: "nprd-sit" } 
    nprd-sit1: {ParentEnv: "nprd-sit1" } 
    nprd-sit2: { ParentEnv: "nprd-sit2" } 
    nprd-sit3: { ParentEnv: "nprd-sit3" }
    nprd-sit-a: { ParentEnv: "nprd-sit" } 
    nprd-sit-b: {ParentEnv: "nprd-sit" } 
    nprd-sit-c: {ParentEnv: "nprd-sit" }
    nprd-uat: { ParentEnv: "nprd-uat" } 
    nprd-uat-a: { ParentEnv: "nprd-uat" } 
    nprd-uat-b: {ParentEnv: "nprd-uat" } 
    nprd-uat-c: {ParentEnv: "nprd-uat" }
    nprd-pt: { ParentEnv: "nprd-pt" } 
    nprd-pp: { ParentEnv: "nprd-pp" } 
    nprd-pp-a: { ParentEnv: "nprd-pp" } 
    nprd-pp-b: { ParentEnv: "nprd-pp" }
    nprd-pp-c: { ParentEnv: "nprd-pp" }

Resources:
  dbConnectionStringSecret:
    Type: 'AWS::SecretsManager::Secret'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Name: !Sub ${AppShortName}-${EnvName}-docker-ConnectionStrings
      Description: 'Secret Key for db connection'
      KmsKeyId: 
        Fn::Sub: 
          - '{{resolve:ssm:${ParamName}}}'
          - ParamName: !Sub 
              - ${AppShortName}-${ParentEnvName}-parameter-EKSkmsKeyId
              - ParentEnvName: !If 
                  - HasSubEnvironment
                  - !FindInMap [EnvironmentMap, !Ref EnvName, ParentEnv]
                  - !Ref EnvName
      Tags:
        - Key: IaCVersion
          Value: InfraPlatform-EKS-v6

  RedisConnectionStringSecret:
    Type: 'AWS::SecretsManager::Secret'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Name: !Sub ${AppShortName}-${EnvName}-docker-Redis
      Description: 'Secret Key for Redis Elasticache Cluster'
      KmsKeyId: 
        Fn::Sub: 
          - '{{resolve:ssm:${ParamName}}}'
          - ParamName: !Sub 
              - ${AppShortName}-${ParentEnvName}-parameter-EKSkmsKeyId
              - ParentEnvName: !If 
                  - HasSubEnvironment
                  - !FindInMap [EnvironmentMap, !Ref EnvName, ParentEnv]
                  - !Ref EnvName
      Tags:
        - Key: IaCVersion
          Value: InfraPlatform-EKS-v6
