AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create S3 buckets with enhanced security features

Parameters:
  AppShortName:
    Type: String
    Description: Short name of the application.
    MinLength: 1
    MaxLength: 10
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: Must contain only alphanumeric characters.

  AWSEnvName:
    Type: String
    Description: Environment
    MinLength: 1
    MaxLength: 10
    ConstraintDescription: Must contain only alphanumeric characters.
    AllowedValues:
      - nprd
      - prod

Conditions:
  IsProduction: !Equals [!Ref AWSEnvName, "prod"]

Resources:
  AppArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: 
        Fn::Sub: "${AppShortName}-${AWSEnvName}-app-artifact"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-AppAuditLog-v4

  AppArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Bucket: !Ref AppArtifactBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceTLSv12orHigher
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt AppArtifactBucket.Arn
              - !Join ['', [!GetAtt AppArtifactBucket.Arn, '/*']]
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt AppArtifactBucket.Arn
              - !Join ['', [!GetAtt AppArtifactBucket.Arn, '/*']]
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  AppRuntimeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: 
        Fn::Sub: "${AppShortName}-${AWSEnvName}-app-runtime"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-AppAuditLog-v4

  AppRuntimeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Bucket: !Ref AppRuntimeBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceTLSv12orHigher
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt AppRuntimeBucket.Arn
              - !Join ['', [!GetAtt AppRuntimeBucket.Arn, '/*']]
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt AppRuntimeBucket.Arn
              - !Join ['', [!GetAtt AppRuntimeBucket.Arn, '/*']]
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  DataLakeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      BucketName: 
        Fn::Sub: "${AppShortName}-${AWSEnvName}-data-lake"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-AppAuditLog-v4

  DataLakeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Bucket: !Ref DataLakeBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceTLSv12orHigher
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt DataLakeBucket.Arn
              - !Join ['', [!GetAtt DataLakeBucket.Arn, '/*']]
            Condition:
              NumericLessThan:
                s3:TlsVersion: 1.2
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !GetAtt DataLakeBucket.Arn
              - !Join ['', [!GetAtt DataLakeBucket.Arn, '/*']]
            Condition:
              Bool:
                aws:SecureTransport: 'false'

