AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to provision and deploy a private API with swagger json file
Parameters:
  AppShortName:
    Description: Application name
    Type: String

  EnvName:
    Description: Environment Name
    Type: String
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-dev1
      - nprd-dev2
      - nprd-stg
      - nprd-sit1
      - nprd-sit2
      - nprd-sit3
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-sit-c
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b
      - nprd-uat-c      
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - nprd-pp-c
      - prod
      - prod-a
      - prod-b
      - prod-c
  SwaggerFile:
    Description: Swagger File location and filename, s3bucketname/filename
    Type: String
  ApigwVpceId:
    Type: String
    Description: VPC Endpoint ID for APIGW, execute-api
  APIName:
    Type: String
    Description: API Name
  StageName:
    Description: Stage Name for api setup, Use dev for non-prod env and prod for production env
    Type: String
  CustomDomainName:
    Type: String
    Description: The custom domain name for the API Gateway (e.g., api.example.com).
  SSLCertificateArn:
    Type: String
    Description: The ARN of the SSL certificate for the custom domain name.
  LambdaAuthorizerFunctionArn:
    Type: String
    Description: The ARN of the Lambda Authorizer Function

Conditions:
  EnableCustomDomain: !And
    - !Not [!Equals [!Ref CustomDomainName, ""]]
    - !Not [!Equals [!Ref SSLCertificateArn, ""]]
  EnableLambdaAuthorizer: !Not [!Equals [!Ref LambdaAuthorizerFunctionArn, ""]]
  IsProduction: !Or [!Equals [!Ref "EnvName", "prod"], !Equals [!Ref "EnvName", "prod-a"], !Equals [!Ref "EnvName", "prod-b"], !Equals [!Ref "EnvName", "prod-c"]]

Resources:
  ApiGatewayDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Condition: EnableCustomDomain
    Properties:
      DomainName: !Ref CustomDomainName
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2
          CertificateArn: !Ref SSLCertificateArn

  ApiGatewayBasePathMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Condition: EnableCustomDomain
    Properties:
      DomainName: !Ref ApiGatewayDomainName
      RestApiId: !Ref PrivateApi
      Stage: !Ref StageName
      BasePath: ''   # Leave empty for the root path
    DependsOn:
      - ApiGatewayStage

  PrivateApi:
    Type: 'AWS::ApiGateway::RestApi'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Metadata:
      DependsOn: !If [EnableCustomDomain, !Ref ApiGatewayDomainName, !Ref 'AWS::NoValue']
    Properties:
      Name: !Ref APIName
      Description: API Import from Swagger file
      FailOnWarnings: false
      Body:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub 's3://${SwaggerFile}'
      EndpointConfiguration:
        Types:
          - PRIVATE
        VpcEndpointIds:
          - !Ref ApigwVpceId
      Policy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 'execute-api:Invoke'
            Resource: '*'
            Condition:
              StringEquals:
                aws:SourceVpce: !Ref ApigwVpceId
      Tags:
        - Key: IaCVersion
          Value: AppSubsystem-SPAIntranet-v5

  ApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    DependsOn:
      - PrivateApi
    Properties:
      RestApiId: !Ref PrivateApi

  ApiGatewayStage:
    Type: 'AWS::ApiGateway::Stage'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Properties:
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref PrivateApi
      StageName: !Ref StageName
      TracingEnabled: true
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          LoggingLevel: INFO
          MetricsEnabled: true
          DataTraceEnabled: true

  ApiGatewayAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    Condition: EnableLambdaAuthorizer
    Properties:
      Name: 'LambdaAuthorizer'
      Type: 'REQUEST'  # You can also use 'REQUEST' based on your use case
      AuthorizerUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaAuthorizerFunctionArn}/invocations'
      IdentitySource: 'method.request.header.Authorization'
      RestApiId: !Ref PrivateApi

  # ApiGatewayIdSSMParameter:
  #   Type: 'AWS::SSM::Parameter'
  #   Properties:
  #     Name: !Sub '/frontendspa/intranet/${AppShortName}/${EnvName}/apigw_id'
  #     Type: 'String'
  #     Value: !Ref PrivateApi
  #     Description: !Sub 'API Gateway ID for ${APIName}'
