AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an ECS Cluster and ECS Task Execution Role with custom managed policies

Parameters:
  AppShortName:
    Description: Application name
    Type: String

  EnvName:
    Description: Env Name
    Type: String
    AllowedValues:
      - nprd
      - nprd-dev
      - nprd-sit1
      - nprd-sit2
      - nprd-sit
      - nprd-sit-a
      - nprd-sit-b
      - nprd-uat
      - nprd-uat-a
      - nprd-uat-b      
      - nprd-pt
      - nprd-pp
      - nprd-pp-a
      - nprd-pp-b
      - prod
      - prod-a
      - prod-b
  
  ECSClusterName:
    Description: ECS Cluster name
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the ECS tasks will run

  Subnets:
    Type: CommaDelimitedList
    Description: The list of Subnets in your Virtual Private Cloud (VPC)
    Default: subnet-08170d48a795103d2,subnet-083fba964c347656f,subnet-0e54709c5b9c524e1

  VPCSubnetCidrAppAZ1:
    Type: String
    Description: VPC Subnet CIDR for App AZ1

  VPCSubnetCidrAppAZ2:
    Type: String
    Description: VPC Subnet CIDR for App AZ2

  VPCSubnetCidrAppAZ3:
    Type: String
    Description: VPC Subnet CIDR for App AZ3
    Default: ''

  ADOTContainerImage:
    Type: String
    Description: URI of the container image
    Default: 781576980265.dkr.ecr.ap-southeast-1.amazonaws.com/adot-collector:latest

  ADOTTaskCpu:
    Type: String
    Default: '256'
    Description: CPU units for the task

  ADOTTaskMemory:
    Type: String
    Default: '512'
    Description: Memory for the task in MiB

Conditions:
  HasVPCSubnetCidrAppAZ3: !Not [!Equals [!Ref VPCSubnetCidrAppAZ3, '']]
  IsProduction:
    Fn::Or:
      - Fn::Equals: [!Ref EnvName, prod]
      - Fn::Equals: [!Ref EnvName, prod-a]
      - Fn::Equals: [!Ref EnvName, prod-b]
      
Resources:
  ServiceConnectNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name:  !Sub "${AppShortName}-${EnvName}.local"
      Vpc: !Ref VpcId

  ServiceConnectNamespaceArnSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/ecs/serviceconnect/namespacearn'
      Type: String
      Value: !GetAtt ServiceConnectNamespace.Arn
      Description: ARN of the Service Connect namespace

  ADOTECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: adot-collector
      Cpu: !Ref ADOTTaskCpu
      Memory: !Ref ADOTTaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      TaskRoleArn: !Ref ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: adot-collector
          Image: !Ref ADOTContainerImage
          PortMappings: 
            - ContainerPort: 4317
              Name: otlp-grpc
            - ContainerPort: 4318
              Name: otlp-http
            - ContainerPort: 13133
              Name: healthcheck
          Environment:
            - Name: AOT_CONFIG_CONTENT 
              Value: !Sub |
                extensions:
                  health_check:
                    endpoint: 0.0.0.0:13133
                receivers:
                  otlp:
                    protocols:
                      grpc:
                        endpoint: 0.0.0.0:4317
                      http:
                        endpoint: 0.0.0.0:4318
                exporters:
                  awsxray:
                    region: "${AWS::Region}"
                  logging:
                    verbosity: "basic"
                processors:
                  memory_limiter:
                    limit_mib: 100
                    check_interval: 5s
                  batch:
                    timeout: 1s
                    send_batch_size: 8192
                  resourcedetection:
                    detectors: [ecs]
                    timeout: 2s
                service:
                  extensions: [health_check]
                  pipelines:
                    traces:
                      receivers: [otlp]
                      processors: [memory_limiter, resourcedetection, batch]
                      exporters: [awsxray, logging]
                  telemetry:
                    logs:
                      level: "error"
          HealthCheck:
            Command: ["/healthcheck"]
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ADOTECSServiceLogGroup
              awslogs-region: ap-southeast-1
              awslogs-stream-prefix: ecs

  ADOTECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: adot-collector-service
      Cluster: !Sub "${AppShortName}-${EnvName}-${ECSClusterName}"
      TaskDefinition: !Ref ADOTECSTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref Subnets
          SecurityGroups: [!Ref ADOTECSServiceSecurityGroup]
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: !GetAtt ServiceConnectNamespace.Arn
        Services:
          - PortName: otlp-grpc
            DiscoveryName: adot-collector
            ClientAliases:
              - Port: 4317

  ADOTECSServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ADOT Collector
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 4317
          ToPort: 4318
          SourceSecurityGroupId: !Sub "{{resolve:ssm:/${AppShortName}/${EnvName}/ecs-alb-security-group-id}}"
        - IpProtocol: tcp
          FromPort: 4317
          ToPort: 4318
          CidrIp: !Ref VPCSubnetCidrAppAZ1
          Description: App Subnet CIDR AZ1
        - IpProtocol: tcp
          FromPort: 4317
          ToPort: 4318
          CidrIp: !Ref VPCSubnetCidrAppAZ2
          Description: App Subnet CIDR AZ2
        - !If
          - HasVPCSubnetCidrAppAZ3
          - IpProtocol: tcp
            FromPort: 4317
            ToPort: 4318
            CidrIp: !Ref VPCSubnetCidrAppAZ3
            Description: Allow traffic from AZ3
          - !Ref AWS::NoValue
          
  ADOTECSServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: adot-collector-service
      RetentionInDays: 7

  ECSkmsKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      Description: KMS key for container secret keys
      EnableKeyRotation: false
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: 'kms:*'
            Resource: '*'

  ECSkmsKeyAlias:
    Type: 'AWS::KMS::Alias'
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      AliasName: !Sub alias/${AppShortName}-${EnvName}-kms-ecs-secretsencryption
      TargetKeyId: !Ref ECSkmsKey
      
  ECSCluster:
    Type: AWS::ECS::Cluster
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      ClusterName: !Sub "${AppShortName}-${EnvName}-${ECSClusterName}"
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  ECSTaskECRPolicy:
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      ManagedPolicyName: !Sub "${AppShortName}-${EnvName}-ECSTaskECR"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetAuthorizationToken"
            Resource: "*"

  ECSTaskCloudWatchPolicy:
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      ManagedPolicyName: !Sub "${AppShortName}-${EnvName}-ECSTaskCloudWatch"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "logs:DescribeLogStreams"
              - "logs:DescribeLogGroups"
              - "cloudwatch:PutMetricData"
              - "cloudwatch:GetMetricStatistics"
              - "cloudwatch:ListMetrics"
              - "cloudwatch:DescribeAlarms"
            Resource: 
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/*:*"
              - !Sub "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:*"


  ECSTaskSSMPolicy:
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      ManagedPolicyName: !Sub "${AppShortName}-${EnvName}-ECSTaskSSM"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "ssmmessages:CreateControlChannel"
              - "ssmmessages:CreateDataChannel"
              - "ssmmessages:OpenControlChannel"
              - "ssmmessages:OpenDataChannel"
              - "ecs:ExecuteCommand"
            Resource: "*"

  PolicySecretsManagerAccess:
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      ManagedPolicyName: !Sub "${AppShortName}-${EnvName}-secretsmanageraccess"
      Description: Policy to allow access to container secret keys
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'secretsmanager:GetResourcePolicy'
              - 'secretsmanager:GetSecretValue'
              - 'kms:Decrypt'
              - 'secretsmanager:DescribeSecret'
              - 'secretsmanager:ListSecretVersionIds'
            Resource:
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppShortName}-${EnvName}-docker-*"
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppShortName}-${EnvName}-a-docker-*"
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppShortName}-${EnvName}-b-docker-*"
              - !GetAtt ECSkmsKey.Arn
          - Effect: Allow
            Action:
              - 'secretsmanager:GetRandomPassword'
              - 'secretsmanager:ListSecrets'
            Resource: '*'

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    DependsOn:
      - ECSTaskECRPolicy
      - ECSTaskCloudWatchPolicy
      - ECSTaskSSMPolicy
      - PolicySecretsManagerAccess
    DeletionPolicy: !If [IsProduction, Retain, Delete]
    UpdateReplacePolicy: !If [IsProduction, Retain, Delete]
    Properties:
      RoleName: !Sub "${AppShortName}-${EnvName}-ecsTaskExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref ECSTaskECRPolicy
        - !Ref ECSTaskCloudWatchPolicy
        - !Ref ECSTaskSSMPolicy
        - !Ref PolicySecretsManagerAccess
        - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  ECSTaskExecutionRoleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppShortName}/${EnvName}/ECSTaskExecutionRoleArn"
      Type: String
      Value: !GetAtt ECSTaskExecutionRole.Arn
      Description: ARN of the ECS Task Execution Role